version: '3'
name: rust_flutter_application
services:
  mysql:
    image: mysql:latest
    container_name: rfa_mysql
    env_file:
      - ./.env
    ports:
      - '6500:3306'
    volumes:
      - rfa_mysql_volume:/var/lib/mysql
volumes:
  rfa_mysql_volume:
